if echo "$-" | grep i > /dev/null; then
  for file in ~/dotfiles/bash/{basic,paths,bash_prompt,aliases,completions,functions}; do
    source $file;
  done;
  unset file;
fi

# use .localrc for settings specific to one system
if [ -r ~/.localrc ]; then
  source ~/.localrc
fi

if [ -r ~/.bashrc.local ]; then
  source ~/.bashrc.local
fi