if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi;

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
if [ -f ~/.profile ]; then
    source ~/.profile
fi;

if [ -d "$HOME/.rbenv" ]; then
  export PATH="$HOME/.rbenv/bin:$PATH";
  eval "$(rbenv init -)";
fi;

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/sdavis/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/sdavis/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/sdavis/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/sdavis/Downloads/google-cloud-sdk/completion.bash.inc'; fi
. "$HOME/.cargo/env"
